name: Rspec

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[ci-skip]') && !contains(github.event.head_commit.message, '[skip-ci]')"
    name: "Ruby: ${{ matrix.ruby }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # 3.0 is interpreted as 3
        ruby: [2.6, 2.7, "3.0", 3.1, 3.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby & 'bundle install'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Test
        run: |
          ruby -v
          bundle exec rspec
        env:
          CI: true
