name: Release Gem

on:
  push:
    tags:
      - "v*"

jobs:
  release_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lsegal/github-release-from-changelog-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Gem
        uses: dawidd6/action-publish-gem@v1.2.0
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
          github_token: ${{secrets.GITHUB_TOKEN}}
